"""wardrobe_items with pgvector

Revision ID: 18b467614a8f
Revises: 
Create Date: 2026-07-21 01:01:30.807426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '18b467614a8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wardrobe_items',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('raw_image_url', sa.Text(), nullable=False),
    sa.Column('processed_image_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='ingestion_status'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('TOP', 'BOTTOM', 'OUTERWEAR', 'DRESS', 'FOOTWEAR', 'ACCESSORY', name='garment_category'), nullable=True),
    sa.Column('sub_category', sa.String(length=64), nullable=True),
    sa.Column('primary_color', sa.String(length=32), nullable=True),
    sa.Column('secondary_color', sa.String(length=32), nullable=True),
    sa.Column('pattern', sa.String(length=32), nullable=True),
    sa.Column('fit', sa.String(length=32), nullable=True),
    sa.Column('material', sa.String(length=64), nullable=True),
    sa.Column('season_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_wardrobe_items_category'), 'wardrobe_items', ['category'], unique=False)
    op.create_index(op.f('ix_wardrobe_items_status'), 'wardrobe_items', ['status'], unique=False)
    op.create_index('ix_wardrobe_items_style_embedding', 'wardrobe_items', ['style_embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'style_embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_wardrobe_items_user_id'), 'wardrobe_items', ['user_id'], unique=False)
    op.create_index('ix_wardrobe_user_category', 'wardrobe_items', ['user_id', 'category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("wardrobe_items")
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wardrobe_user_category', table_name='wardrobe_items')
    op.drop_index(op.f('ix_wardrobe_items_user_id'), table_name='wardrobe_items')
    op.drop_index('ix_wardrobe_items_style_embedding', table_name='wardrobe_items', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'style_embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_wardrobe_items_status'), table_name='wardrobe_items')
    op.drop_index(op.f('ix_wardrobe_items_category'), table_name='wardrobe_items')
    op.drop_table('wardrobe_items')
    # ### end Alembic commands ###
